language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
jobs:
  include:
    - stage: deploy
      rust: stable
      script: skip
      before_deploy:
        - rustup target add x86_64-unknown-linux-musl
        - rustup target add i686-unknown-linux-musl
        - cargo build --target x86_64-unknown-linux-musl --release
        - zip x86_64-unknown-linux-musl.zip target/x86_64-unknown-linux-musl/release/add
        - cargo build --target i686-unknown-linux-musl --release
        - zip i686-unknown-linux-musl.zip target/i686-unknown-linux-musl/release/add
      deploy:
        provider: releases
        api_key:
          secure: PqAl1stZcnlysQ/9VltQ6XQS+O9KmJ1t39GKFqzKqafx4h0EN383Iqkah5Ont7zJ2nDfPzzUyp5q7H4zfKptdQlkB5sXtmPoPsggD6VLG5FX9q/tmEVA04FaKGys7WRPMHu7MJxNVwGWnzDenAjLcsR33OgT84AiflDk65/Mz9vrY0XBxNu105pl/3jkr4N+q1CaLfTvocNr+DhRUKPoxg5pzbg0hEYZ2iUCoJ//V7aS7uesa6FKBmxwmbPDoOYDq83FPbGs494jtgbOgg59mccRoZqFlJ/pKC6QAsnlgTH9+2I94uoHL3tpUzWXGR9vG7k12fSYdS1azpqs3hQ+01H7Yco8JVfQKj0E9YTZP5NbLcA9qVX/AStkhN/69OecU2+mm7WSFoshKr3HcP0tv68Wut6NmDJTUfUpqK9ZDM9yevLAVI/XXsYQd6j6EDDkTiIwZSZajCR72wXOPQLfRpt0Bwaczaf8Va/wfRmPv0+fHWKc5C0TvlULsR06HR7lg0NDknq/pDcghMj/mVSf2vIFtwf9mMgN13vdJLn0ck6NmIPxO6mLH59Ygpqm0OKzLovCvnlvPgMR2RAposh8o+iY6oPHBn6Lszp/5ONzSR/mT4hI+Fy/kHOi3mcaOAdrn8MR/dOW1HyEFhrewreiAwq5fCKY+mx9whEKBt5k9hA=
        file:
          - x86_64-unknown-linux-musl.zip
          - i686-unknown-linux-musl.zip
        skip_cleanup: true
        on:
          tags: true