[package]
name = "add-rs"
version = "0.2.0"
authors = ["Oscar David Arbeláez <oscar.arbelaez@epfl.ch>"]
edition = "2018"

[dependencies]
docopt = "1"
serde = { version = "1", features = ["derive"] }

[[bin]]
name = "add"
path = "src/main.rs"